# Generated by Django 5.2.5 on 2025-09-06 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "CUSTOMER_ID",
                    models.AutoField(
                        db_column="CUSTOMERID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "NAME",
                    models.CharField(
                        db_column="CUSTOMERNAME", default="UNKNOWN", max_length=100
                    ),
                ),
                (
                    "MOBILE_NO",
                    models.CharField(
                        db_column="MOBILE", default="0000000000", max_length=15
                    ),
                ),
                ("ADDRESS", models.TextField(db_column="ADDRESS", default="N/A")),
                (
                    "CITY",
                    models.CharField(db_column="CITY", default="N/A", max_length=50),
                ),
                (
                    "TOWN",
                    models.CharField(db_column="TOWN", default="N/A", max_length=50),
                ),
                ("PINCODE", models.IntegerField(db_column="PINCODE", default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "EMPLOYEE_ID",
                    models.AutoField(
                        db_column="EMPLOYEEID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "NAME",
                    models.CharField(
                        db_column="EMPLOYEENAME", default="UNKNOWN", max_length=100
                    ),
                ),
                (
                    "MOBILE_NO",
                    models.CharField(
                        db_column="MOBILENO", default="0000000000", max_length=15
                    ),
                ),
                ("ADDRESS", models.TextField(db_column="ADDRESS", default="N/A")),
                ("DOB", models.DateField(blank=True, db_column="DOB", null=True)),
                ("AGE", models.IntegerField(db_column="AGE", default=0)),
                ("DOJ", models.DateField(blank=True, db_column="DOJ", null=True)),
                (
                    "GENDER",
                    models.CharField(
                        db_column="GENDER", default="NOT_SPECIFIED", max_length=10
                    ),
                ),
                (
                    "EMAIL_ID",
                    models.EmailField(
                        db_column="EMAILID",
                        default="unknown@example.com",
                        max_length=254,
                    ),
                ),
                (
                    "QUALIFICATION",
                    models.CharField(
                        db_column="QUALIFICATION", default="N/A", max_length=100
                    ),
                ),
                (
                    "DESIGNATION",
                    models.CharField(
                        db_column="DESIGNATION", default="STAFF", max_length=100
                    ),
                ),
                ("BASIC_PAY", models.FloatField(db_column="BASICPAY", default=0.0)),
                ("INCENTIVE", models.FloatField(db_column="INCENTIVE", default=0.0)),
                ("NET_PAY", models.FloatField(db_column="NETPAY", default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Pincode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PINCODE", models.IntegerField(unique=True)),
                ("CITY", models.CharField(blank=True, max_length=100)),
                ("STATE", models.CharField(blank=True, max_length=100)),
                ("TOWN", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "CATEGORY",
                    models.CharField(
                        db_column="CATEGORY", default="GENERAL", max_length=50
                    ),
                ),
                (
                    "PRODUCT_NAME",
                    models.CharField(
                        db_column="PRODUCTNAME", default="UNKNOWN", max_length=100
                    ),
                ),
                (
                    "BRAND_NAME",
                    models.CharField(
                        db_column="BRANDNAME", default="UNKNOWN", max_length=100
                    ),
                ),
                ("STOCK", models.IntegerField(db_column="STOCK", default=0)),
                ("MRP", models.FloatField(db_column="MRP", default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("ORDERID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "SUPPLIER_ID",
                    models.IntegerField(db_column="SUPPLIER_ID", default=0),
                ),
                (
                    "SUPPLIER_NAME",
                    models.CharField(
                        db_column="SUPPLIER_NAME", default="UNKNOWN", max_length=100
                    ),
                ),
                ("CATEGORY", models.CharField(default="GENERAL", max_length=100)),
                ("PRODUCTNAME", models.CharField(default="UNKNOWN", max_length=100)),
                (
                    "PRICE",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("QUANTITY_REQUIRED", models.IntegerField(default=0)),
                (
                    "TOTAL_PRICE",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("DATE", models.CharField(default="N/A", max_length=50)),
                ("TIME", models.CharField(default="N/A", max_length=50)),
                ("PENDING_QUANTITY", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "SUPPLIER_ID",
                    models.AutoField(
                        db_column="SUPPLIERID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "NAME",
                    models.CharField(
                        db_column="SUPPLIERNAME", default="UNKNOWN", max_length=100
                    ),
                ),
                (
                    "COMPANY_NAME",
                    models.CharField(
                        db_column="COMPANYNAME", default="UNKNOWN", max_length=100
                    ),
                ),
                (
                    "MOBILE_NO",
                    models.CharField(
                        db_column="MOBILENO", default="0000000000", max_length=15
                    ),
                ),
                (
                    "EMAIL_ID",
                    models.EmailField(
                        db_column="EMAILID",
                        default="unknown@example.com",
                        max_length=254,
                    ),
                ),
                (
                    "CATEGORY",
                    models.CharField(
                        db_column="CATEGORY", default="GENERAL", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "BILL_NO",
                    models.AutoField(
                        db_column="BILLNO", primary_key=True, serialize=False
                    ),
                ),
                (
                    "CATEGORY",
                    models.CharField(
                        db_column="CATEGORY", default="GENERAL", max_length=50
                    ),
                ),
                ("QUANTITY", models.IntegerField(db_column="QUANTITY", default=0)),
                ("PRICE", models.FloatField(db_column="PRICE", default=0.0)),
                ("TOTAL_PRICE", models.FloatField(db_column="TOTALPRICE", default=0.0)),
                (
                    "BILL_DATE",
                    models.DateField(blank=True, db_column="BILLDATE", null=True),
                ),
                (
                    "CUSTOMER",
                    models.ForeignKey(
                        blank=True,
                        db_column="CUSTOMERID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.customer",
                    ),
                ),
                (
                    "PRODUCT",
                    models.ForeignKey(
                        db_column="PRODUCTID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SUPPLIER_NAME",
                    models.CharField(
                        db_column="SUPPLIERNAME", default="UNKNOWN", max_length=100
                    ),
                ),
                ("SUPPLIER_ID", models.IntegerField(db_column="SUPPLIERID", default=0)),
                (
                    "PRODUCTNAME",
                    models.CharField(
                        db_column="PRODUCTNAME", default="UNKNOWN", max_length=100
                    ),
                ),
                (
                    "CATEGORY",
                    models.CharField(
                        db_column="CATEGORY", default="GENERAL", max_length=100
                    ),
                ),
                (
                    "RECEIVED_QUANTITY",
                    models.IntegerField(db_column="RECEIVEDQUANTITY", default=0),
                ),
                (
                    "RECEIVED_DATE",
                    models.DateField(blank=True, db_column="RECEIVEDDATE", null=True),
                ),
                (
                    "ORDERED_QUANTITY",
                    models.IntegerField(db_column="ORDEREDQUANTITY", default=0),
                ),
                (
                    "PENDING_QUANTITY",
                    models.IntegerField(db_column="PENDINGQUANTITY", default=0),
                ),
                (
                    "ORDER",
                    models.ForeignKey(
                        db_column="ORDERID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ITEMENTRIES",
                        to="api.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("STOCK", models.IntegerField(db_column="STOCK", default=0)),
                (
                    "PRODUCT",
                    models.ForeignKey(
                        db_column="PRODUCTID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="STOCK_RECORD",
                        to="api.product",
                    ),
                ),
            ],
        ),
    ]
