# Generated by Django 5.2.5 on 2025-09-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="EMPLOYEE",
            field=models.ForeignKey(
                blank=True,
                db_column="EMPLOYEEID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.employee",
            ),
        ),
    ]
